### ISSUE TITLE
Site is dead. Github Pages?

### ISSUE THREAD

**Issue by virzen** [EvanBalster/TiddlyWikiFormula#25]
The site with demonstration wiki seems to have expired. How about uploading it to Github Pages so it's hosted for free? @EvanBalster

**Comment by joshuafontany** [comment]
I have forked this plugin and have been keeping the Patch tiddlers up to date with the current TiddlyWiki5 pre-release.

https://github.com/joshuafontany/TiddlyWikiFormula

https://joshuafontany.github.io/TiddlyWikiFormula/

Best,
Joshua Fontany

**Comment by EvanBalster** [comment]
My site's domain registration has been held up by a technical meltdown with my registrar and I'll be transferring it to another at my earliest opportunity.  Apologies to the TiddlyWiki community for the loss of service; I would be happy to host the Formulas wiki on one of my other sites if someone can update the relevant links.

**Josh** — I'd be happy to authorize you to commit to the main repository here, if you like.  Sorry for being off the map and thanks for maintaining this project.  My ability to work on side projects took a dive after an injury last year and since my recovery I've been overwhelmingly busy growing my little company!

**Comment by joshuafontany** [comment]
Formulas has been updated to be compatible with TW5.1.23. Thanks for the permissions, @EvanBalster! Closing this issue as resolved. :)
