### ISSUE TITLE
There seems to be Mallware at https://evanbalster.com/tiddlywiki/formulas.html

### ISSUE THREAD

**Issue by AnthonyMuscio** [EvanBalster/TiddlyWikiFormula#31]
Evan,

I hope you are well, I have not heard from you much. The community is now also on [Discourse](https://talk.tiddlywiki.org), do join.

There seems to be Mallware at https://evanbalster.com/tiddlywiki/formulas.html and as a result I can access the demo/documentation (which is not included in the plugin)

Regards Tones

**Comment by EvanBalster** [comment]
I lost control of evanbalster.com about a year ago due to an issue with my registrar.  There isn't much I can do about it now other than filing a UDRP complaint.

The link in README.md goes to a copy on @joshuafontany's website, which has the latest documentation.

I'm still tinkering with all kinds of things, some of which are powered by TiddlyWiki, but my focus is elsewhere lately.

**Comment by EvanBalster** [comment]
The evanbalster.com URL is no longer linked from this GitHub, so I'll close this issue.
